import { useEffect, useMemo, useState } from "react";
import api from "../../api";
const labels = { pending: "Chờ xác nhận", confirmed: "Đã xác nhận", completed: "Hoàn thành", cancelled: "Đã hủy" };
const money = v => `${Number(v || 0).toLocaleString("vi-VN")} đ`;
const total = b => (b.services?.length ? b.services : [b.service]).filter(Boolean).reduce((s, x) => s + Number(x.price || 0), 0) + (b.selectedSubServices || []).reduce((s, x) => s + Number(x.price || 0), 0);
export default function Bookings() {
    const [list, setList] = useState([]), [staff, setStaff] = useState([]), [filter, setFilter] = useState("all"), [message, setMessage] = useState("");
    const load = async () => { try { const [a, e] = await Promise.all([api.get("/appointments/admin/all"), api.get("/employees")]); setList(Array.isArray(a.data) ? a.data : []); setStaff(Array.isArray(e.data) ? e.data : []); setMessage("") } catch (err) { setMessage(err.response?.data?.message || "Không tải được lịch hẹn.") } };
    useEffect(() => { load(); const t = setInterval(load, 5000); return () => clearInterval(t) }, []);
    const assign = async (id, employee) => { try { if (!employee) return setMessage("Vui lòng chọn nhân viên."); await api.put(`/appointments/${id}/assign`, { employee }); await load(); setMessage("Đã xếp nhân viên thành công.") } catch (e) { setMessage(e.response?.data?.message || "Không thể xếp nhân viên.") } };
    const status = async (id, value) => { try { let reason = ""; if (value === "cancelled") { reason = window.prompt("Lý do hủy đơn (có thể để trống):", "") ?? "" } await api.put(`/appointments/${id}/status`, { status: value, cancellationReason: reason }); await load(); setMessage(value === "cancelled" ? "Đã hủy đơn thành công." : "Đã cập nhật trạng thái.") } catch (e) { setMessage(e.response?.data?.message || "Không thể đổi trạng thái.") } };
    const filtered = useMemo(() => filter === "all" ? list : list.filter(x => x.status === filter), [list, filter]);
    const counts = { all: list.length, pending: list.filter(x => x.status === "pending").length, confirmed: list.filter(x => x.status === "confirmed").length, completed: list.filter(x => x.status === "completed").length, cancelled: list.filter(x => x.status === "cancelled").length };
    return <main className="container page"><div className="page-title-row"><div><span className="section-kicker">ĐƠN HÀNG</span><h1>Quản lý đơn / lịch hẹn</h1><p className="muted">Theo dõi đơn đã hủy, hủy đơn khi cần và khôi phục trạng thái trước khi hoàn thành.</p></div><button className="outline-btn" onClick={load}>↻ Làm mới</button></div>
        {message && <div className="error">{message}</div>}
        <div className="booking-filters">{Object.entries({ all: "Tất cả", pending: "Chờ xác nhận", confirmed: "Đã xác nhận", completed: "Hoàn thành", cancelled: "Đã hủy" }).map(([key, label]) => <button key={key} className={filter === key ? "active" : ""} onClick={() => setFilter(key)}>{label} <b>{counts[key]}</b></button>)}</div>
        <div className="tablewrap"><table><thead><tr><th>Khách hàng</th><th>Dịch vụ</th><th>Ngày / giờ</th><th>Nhân viên</th><th>Giá trị</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{filtered.length ? filtered.map(b => <tr key={b._id}><td><strong>{b.customer?.name || b.customerName}</strong><br /><small>{b.customerPhone || b.customer?.phone || "—"}</small></td><td>{(b.services?.length ? b.services : [b.service]).filter(Boolean).map(x => x.name).join(" + ")}</td><td>{b.date}<br />{b.time}</td><td><select value={b.employee?._id || ""} onChange={e => assign(b._id, e.target.value)} disabled={b.status === "cancelled"}><option value="">-- Chọn --</option>{staff.map(e => <option key={e._id} value={e._id}>{e.name}</option>)}</select></td><td><strong>{money(total(b))}</strong></td><td><select value={b.status} onChange={e => status(b._id, e.target.value)}><option value="pending">{labels.pending}</option><option value="confirmed">{labels.confirmed}</option><option value="completed">{labels.completed}</option><option value="cancelled">{labels.cancelled}</option></select>{b.status === "cancelled" && <small className="cancel-note">{b.cancellationReason || "Không ghi lý do"}</small>}</td><td>{b.status !== "cancelled" && b.status !== "completed" ? <button className="danger" onClick={() => status(b._id, "cancelled")}>Hủy đơn</button> : b.status === "cancelled" ? <button className="outline-btn small-btn" onClick={() => status(b._id, "pending")}>Mở lại đơn</button> : <span className="muted">Đã hoàn thành</span>}</td></tr>) : <tr><td colSpan="7" style={{ textAlign: "center" }}>Không có đơn phù hợp.</td></tr>}</tbody></table></div></main>
}