import { useEffect, useState } from "react";
import api from "../../api";

export default function Schedules() {
  const [staff, setStaff] = useState([]), [schedules, setSchedules] = useState([]), [message, setMessage] = useState("");
  const [f, setF] = useState({ employee: "", date: "", startTime: "09:00", endTime: "17:00" });
  const load = async () => { const [e, s] = await Promise.all([api.get("/employees"), api.get("/schedules")]); setStaff(e.data); setSchedules(s.data.schedules); if (!f.employee && e.data[0]) setF(x => ({ ...x, employee: e.data[0]._id })); };
  useEffect(() => { load().catch(err => setMessage(err.response?.data?.message || "Không tải được ca làm.")); }, []);
  const add = async () => { try { setMessage(""); if (!f.employee || !f.date) return setMessage("Vui lòng chọn nhân viên và ngày."); await api.post("/schedules/work", f); setMessage("Đã xếp ca vào MongoDB."); await load(); } catch (err) { setMessage(err.response?.data?.message || "Không thể thêm ca."); } };
  const remove = async id => { if (!confirm("Xóa ca này?")) return; await api.delete(`/schedules/work/${id}`); await load(); };
  return <main className="container page"><h1>Ca làm & ngày nghỉ</h1>{message && <div className="error">{message}</div>}<div className="formbox"><h2>Xếp ca cho nhân viên</h2><select value={f.employee} onChange={e => setF({ ...f, employee: e.target.value })}>{staff.map(x => <option key={x._id} value={x._id}>{x.name}</option>)}</select><input type="date" value={f.date} onChange={e => setF({ ...f, date: e.target.value })} /><div className="split"><input type="time" value={f.startTime} onChange={e => setF({ ...f, startTime: e.target.value })} /><input type="time" value={f.endTime} onChange={e => setF({ ...f, endTime: e.target.value })} /></div><button className="btn" onClick={add}>Xếp ca</button></div><h2>Danh sách ca trong MongoDB</h2><div className="tablewrap"><table><thead><tr><th>Nhân viên</th><th>Ngày</th><th>Giờ</th><th></th></tr></thead><tbody>{schedules.map(x => <tr key={x._id}><td>{x.employee?.name}</td><td>{x.date || `Thứ ${x.dayOfWeek}`}</td><td>{x.startTime} - {x.endTime}</td><td><button onClick={() => remove(x._id)}>Xóa</button></td></tr>)}</tbody></table></div></main>;
}